apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: my-flask-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "oracle-db-service"
        - name: DB_PORT
          value: "1521"
        - name: DB_SERVICE
          value: "FREEPDB1"
        - name: DB_USER
          value: "system"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oracle-db-secrets
              key: db-password